configfile: "config/config.yaml"

AB1 = config["AB1"]
Renca = config["Renca"]
tagged = config["HATag"]
allsamples = AB1 + Renca

rule all:
    pass

include: "workflow/rules/file_download.smk"
include: "workflow/rules/preprocess_samples.smk",
include: "workflow/rules/ab1_tumour.smk",
include: "workflow/rules/renca_tumour.smk",
include: "workflow/rules/cellrouter.smk",
include: "workflow/rules/velocyto.smk",
include: "workflow/rules/scde.smk",
include: "workflow/rules/phenopath.smk",
include: "workflow/rules/SCENIC.smk",
include: "workflow/rules/test_data_creation.smk",

